Programming for Data Analysis - Assignment 2019
=================================================

#### Eoghan Delaney

## Task 1. Explaining the package
***

    Numpy -
***

In [24]:
import numpy as np

NumPy defines itself as 'the fundamental package for scientific computing with Python' [1]. Some of its features include a powerful N-dimentional array object, sophisticated functions, tools for integrating C/C++, Fortran code and finaly linear algebra, fourier transforms and random number capabilites. 

N-dimensional array can provide a multi-dimensional list or list within a list means of storing data, this structre can enable fast and easy calculations and data manipluation.

    NumPy.random -
***

In [25]:
import numpy.random as rand

Utilising all the functionality in numpy, the numpy.random subpackge is a pseudo random value generator. The SciPy documentation [2] identifies that their are two influences on the pseudo random value - the BitGenerator and the Generators, both of which influence the "randomly generated value". 

The BitGenerator - "These are typically unsigned integer words filled with sequences of either 32 or 64 random bits."[2]. The values are then influenced by the generators which are the probility distribution (or the likelyhood something is to happen), these will be discessed further below, but include, The Normal, Exponential, Laplace distributions. This random [3] algorithim is named Mersenne Twister (MT19937).

## Task 2. Explain the use of the “Simple random data” and “Permutations” functions.
***


###     Task 2.1 Simple random Data

Simple Random Data are the following functions that are built atop of the random subpackage in NumPy. In this sction we will explain a nuber of the fuctions.

![title](img/simple_rand_data.PNG)

In [26]:
'''
    numpy.random.rand
    
    The above function generates random values in a given ndarray shape for values from 0-1
    
'''
oneXone = np.random.rand()
twoXtwo = np.random.rand(2,2)
threeXthree = np.random.rand(3,3)

print("Below is a 1x1 ndarray generated by the rand function:" + '\n' + str(oneXone) + '\n')
print("Below is a 2x2 ndarray generated by the rand function:" + '\n' + str(twoXtwo) + '\n')
print("Below is a 3x3 ndarray generated by the rand function:" + '\n' + str(threeXthree) + '\n')

Below is a 1x1 ndarray generated by the rand function:
0.41112367248193105

Below is a 2x2 ndarray generated by the rand function:
[[0.49505963 0.11456612]
 [0.93184444 0.56673079]]

Below is a 3x3 ndarray generated by the rand function:
[[0.69099752 0.18195007 0.04678546]
 [0.35874602 0.3806209  0.63400671]
 [0.00210503 0.04250404 0.91409055]]



In [27]:
'''
    numpy.random.randn
    
    The above function randn acts as the above function rand however it follows the normal statistical distribution and can contain negative values

'''
oneXone = np.random.randn()
twoXtwo = np.random.randn(2,2)
threeXthree = np.random.randn(3,3)

print("Below is a 1x1 ndarray generated by the randn function:" + '\n' + str(oneXone) + '\n')
print("Below is a 2x2 ndarray generated by the randn function:" + '\n' + str(twoXtwo) + '\n')
print("Below is a 3x3 ndarray generated by the randn function:" + '\n' + str(threeXthree) + '\n')

Below is a 1x1 ndarray generated by the randn function:
0.23443201987664228

Below is a 2x2 ndarray generated by the randn function:
[[0.58587274 0.87174648]
 [2.36111003 0.5451756 ]]

Below is a 3x3 ndarray generated by the randn function:
[[ 0.41125368 -0.51836156  1.92609171]
 [-1.12046357  0.05401852  1.54674707]
 [-0.61506829  0.90546912  0.37402289]]



In [28]:
'''
    numpy.random.randint
    
    As before we can generate random numbers, in this case we can randomly generate an ndarray, of interages, above or below a difined value
    
'''

oneXone = np.random.randint(3, size=(1))
twoXtwo = np.random.randint(5,size=(2,2))
threeXthree = np.random.randint(10,size=(3,3))

print("Below is a 1x1 ndarray generated by the randint function, below the int value 3:" + '\n' + str(oneXone) + '\n')
print("Below is a 2x2 ndarray generated by the randint function, below the int value 5::" + '\n' + str(twoXtwo) + '\n')
print("Below is a 3x3 ndarray generated by the randint function, below the int value 10::" + '\n' + str(threeXthree) + '\n')

Below is a 1x1 ndarray generated by the randint function, below the int value 3:
[2]

Below is a 2x2 ndarray generated by the randint function, below the int value 5::
[[0 0]
 [3 1]]

Below is a 3x3 ndarray generated by the randint function, below the int value 10::
[[4 3 9]
 [8 4 5]
 [9 8 3]]



In [29]:
'''
    numpy.random.rand_integers
    
    As before we can generate random number, in this case we can randomly generate an ndarray, of interages, inclusive of a range between two values
    
'''
oneXone = np.random.random_integers(3, high=5, size=(1))
twoXtwo = np.random.random_integers(5, high=10,size=(2,2))
threeXthree = np.random.random_integers(10, high=15, size=(3,3))

print("Below is a 1x1 ndarray generated by the random_integers function, below the int value between 3 and 5:" + '\n' + str(oneXone) + '\n')
print("Below is a 2x2 ndarray generated by the random_integers function, below the int value between 5 and 10:" + '\n' + str(twoXtwo) + '\n')
print("Below is a 3x3 ndarray generated by the random_integers function, below the int value between 10 and 15:" + '\n' + str(threeXthree) + '\n')


Below is a 1x1 ndarray generated by the random_integers function, below the int value between 3 and 5:
[5]

Below is a 2x2 ndarray generated by the random_integers function, below the int value between 5 and 10:
[[10  7]
 [ 7  5]]

Below is a 3x3 ndarray generated by the random_integers function, below the int value between 10 and 15:
[[14 15 11]
 [15 11 11]
 [10 15 15]]



C:\Users\eogha\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: This function is deprecated. Please call randint(3, 5 + 1) instead
  import sys
C:\Users\eogha\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: This function is deprecated. Please call randint(5, 10 + 1) instead
  
C:\Users\eogha\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: This function is deprecated. Please call randint(10, 15 + 1) instead
  if __name__ == '__main__':


In [30]:
'''
    numpy.random.random_sample
    
    As before we can generate random numbers, in this case we can randomly generate an ndarray, of floats, made up of a continuous uniform distribution
    
'''
oneXone = np.random.random_sample((1))
twoXtwo = np.random.random_sample((2,2))
threeXthree = np.random.random_sample((3,3))

''' 
    Other functions that can output the same results are:
        np.random.random()
        np.random.random_ranf()
        np.random.sample()
    
'''

print("Below is a 1x1 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:" + '\n' + str(oneXone) + '\n')
print("Below is a 2x2 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:" + '\n' + str(twoXtwo) + '\n')
print("Below is a 3x3 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:" + '\n' + str(threeXthree) + '\n')


Below is a 1x1 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:
[0.06406441]

Below is a 2x2 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:
[[0.3201087  0.4323002 ]
 [0.36663403 0.73058016]]

Below is a 3x3 ndarray generated by the random_sample function, below the float value of a continuous uniform distribution:
[[0.50376541 0.65108448 0.73932965]
 [0.7327262  0.52121474 0.62519394]
 [0.78591821 0.790884   0.27506895]]



In [31]:
'''
    numpy.random.choice(a, size=None, replace=True, p=None)
    
    As before we can generate random choice, where a is a 1-D array
    Size is an output shape
    p is the probibilites associated with each entry in A.
    
'''
choice = np.random.choice(5, 6,p=[0.1, 0, 0.3, 0.6, 0]) #This was adapted from the numpy documentation
print(choice)

[3 2 2 2 3 2]


In [ ]:
'''
    numpy.random.byte()
    
    The byte function can randomly generate a byte,in the form of a string.
     
'''

byte = np.random.bytes(5)
print(byte)

b'\xb1d\x04\x86\x16'


The above examples describes and demonstrates the various functions for random values in NumPy. These functions are very powerful when analysising problems in data analytics.

### Task 2.2 Permutaions

Permutations in NumPy do not generate any form of values in the 

## Taks 3. Distributions 5 Number
***

In this section we will discuss the numpy.random subpackage which randomly generates statistical distribution samples based on user defined peramiteres, the five selected to discuss in this section are - normal, laplace, exponential, chisquare and binomial.

In [ ]:
''' We import all the graph packages to enable us to view the data visually '''
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

#### 3.1 Normal
***

The normal distribution is the most common probibility distruction in statistics, also known as the Guassian or Bell Curve. The bell shape is created when the data of a guassian distribution is plotted on a graph.

This data is a certain measurable perameter of a group of similar specimens, some examples include heights/weight of a group of people, IQ scores or blood pressure in patients. The average or mean of these datapoints is the top of the bellcurve as it is most likely to accure. The standard deviation is the spread of these perameters. If we were to use the following example, heights of pupils in boys national school - the mean would be the average height of the pupils and the bellcurve would extend to the tallest and smallest student. The normal distribution plotted on the graph would illustrate the majority of pupils are in around average height and as we move away from the centre the extremes become less comman and therefore statistly less likely.

The numpy.random.normal distribution can randomly generate a array following a bell curve probility patern. The mean, standard deviation and size is required followed by the sample size.

In [ ]:
# For this example we pick arbutrey heights for pupils in a class
mean = 1.7 # 1.7m height
stand = 0.1 # 0.2m standard deviation
sample = 1000 #100 pupils in the class

ClassHeight = np.random.normal(mean, stand, sample)
print("The first twenty values of the ndarray are: " + str(ClassHeight[:20]))

The first twenty values of the ndarray are: [1.7624475  1.66470429 1.75385502 1.77519971 1.91984758 1.93126126
 1.65547532 1.76106968 1.56457819 1.74406895 1.61934857 1.66783453
 1.71773711 1.72127125 1.74662865 1.68154053 1.7449212  1.80930739
 1.54106561 1.75928284]


We can now plot the above output on to a graph to give a visual repesentaion

In [ ]:
plt.hist(ClassHeight,25)
plt.xlabel('height (m)')
plt.ylabel('Number of pupils')
plt.title('Normal Dist')
plt.show()

Using the Numpy documentation as reference we can introduce a trendline to give a clear dipition of the bellcurve. [2]

In [ ]:
''' The below code was adapted from the numpy website. To include the distribution line '''

n, bins, patches = plt.hist(ClassHeight,25,density=True)
y =  1/(stand * np.sqrt(2 * np.pi)) * np.exp( - (bins - mean)**2 / (2 * stand**2) )
plt.plot(bins, y, linewidth=2, color='r')

plt.plot(bins, y, 'r--')
plt.xlabel('height (m)')
plt.ylabel('Number of pupils')
plt.title('Normal Dist')
plt.show()

The above data was randomly generated from the normal distrubtion function in numpy package. This data is set to statistly mimic real life distributions based on a predifined standard deviation and mean of the data.

#### 3.2 Exponential
***

Exponential distribution is another statistical distribution that can be generated using the random function in NumPy. The exponential distribution is often concerned with the amount of time until some specific event occurs[4]. Some examples of this include the amount of time a long business call or the page requests to Wikipedia [5].

The two main influences on the exponetial distribution is the scale and the size. The scale is the defined in mathamatical terms as beta or one over lamda. Beta is scale of the distribtion which is the rate of growth or the decay of the graph, how quickly its decays over the size of the samlple [6]. The size is the is the number of instances in which an event accured.

In [ ]:
''' The below is the exponential distribution - for this example we use a scale of 5 and a size of 1000 '''
scale =  1/0.2
size = 1000
time = np.random.exponential(scale, size)
print("The first twenty values of the ndarray are: " + str(time[:20]))

In [ ]:
plt.hist(time, 100)
plt.xlabel('time (min)')
plt.ylabel('Number of instances')
plt.title('Exponential Dist')
plt.show()

#### 3.3 Laplace
***

Laplace distrubtion can be viewed as two exponential distributions butted up against one another.

#### 3.4 Chisquare
***

Chisquare

#### 3.5 Binomial
***

Binomial

## 4. Explain the use of seeds in generating pseudorandom numbers.
***


#### References
***

1. https://numpy.org/
2. https://docs.scipy.org/doc/numpy/reference/random/index.html
3. https://docs.scipy.org/doc/numpy/reference/random/bit_generators/mt19937.html
4. https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(OpenStax)/05%3A_Continuous_Random_Variables/5.3%3A_The_Exponential_Distribution
5. https://docs.scipy.org/doc/numpy-1.15.4/reference/generated/numpy.random.exponential.html
5. https://docs.w3cub.com/numpy~1.14/generated/numpy.random.exponential/
5. https://courses.lumenlearning.com/introstats1/chapter/the-exponential-distribution/
6. https://www.ncetm.org.uk/public/files/20608858/Ch.+5+Exponential+Growth+and+Decay.pdf
6. https://www.youtube.com/watch?v=Ce_tWXEPTtY